### ISSUE TITLE
a package could not be found that allows the action to complete

### ISSUE THREAD

**Issue by NYSMuseum** [sagiadinos/garlic-player#1]
I'm seeing this when trying to open the .deb file in rasbian.  I don't know how to install.

**Comment by sagiadinos** [comment]
Hi,

The currently public .deb-file you can download are compiled for [x64](https://en.wikipedia.org/w/index.php?title=X64) architecture (Intel/AMD). The Rpi has a ARM CPU.

regards
Niko

**Comment by kangfend** [comment]
@sagiadinos how to build this for raspberry pi?
