### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by bladerunner2020** [sagiadinos/garlic-player#10]
I am trying to install garlic-player on Windows 10 home and got error during installation that reads (translated into English):

Error during installation
(com.microsoft.vcredist.x64): Failed to execute (unexpected termination code: 1638): "C:\Program Files (x86)\garlic-player/vcredist_x64.exe /quiet /norestart"

**Comment by sagiadinos** [comment]
I have only windows 7, but I AFAIK you can ignore this error. It means, that the Visual Studio Distributables are already installed. The garlic-player should work.

Did you install a CI-version or the 0.3.0 release?

**Comment by bladerunner2020** [comment]
I installed 0.3.0 release. I pressed button skip and the player actually works.
will try CI-version as well )
