### ISSUE TITLE
Event triggers (possible feature request)

### ISSUE THREAD

**Issue by bladerunner2020** [sagiadinos/garlic-player#11]
Iadea SMIL supports network triggers. We can create a SMIL file and then start one or anther seq via http-requests. 

what is usually needed:
- start a video over net
- stop video
- pause/resume
- control volume of playback

Would it be possible to do or to add something like this to garlic-player?

**Comment by sagiadinos** [comment]
That will happens in the next near time. Currently, there are some conceptional problems in the parser, which needs to address, first. For example for the behaviour of excl/priority has some errors. After that a small webserver will be implemented to offer a REST-API.

P.S.: I do not know how to make a feature request here

**Comment by bladerunner2020** [comment]
Cool. Any idea about when new version with REST-API should be available?

**Comment by sagiadinos** [comment]
I hope until the end of April 2020. It has some business priority for me...

**Comment by sagiadinos** [comment]
Sorry, about delay, but I had to focus on some more urgent projects the last two months. 
I started already to fix the excl/priority issues.

**Comment by sagiadinos** [comment]
Sorry about delay, but I had to focus on some more urgent projects the last two months. 
I started just some days ago to fix the excl/priority issues.

**Comment by sagiadinos** [comment]
With a two year delay finally the notify-trigger for begin and end attributes is supported and reachable via RestFull API. 
The parser clean up for "correct" trigger, better SMIL support and some other projects take much more time than expected. But, better late than never. ;)

Currently status is experimental. You will find binaries on https://garlic-player.com/index.html#downloads under topic "Latest Developer Releases".
