### ISSUE TITLE
Android multiscreen / bigscreen multimonitor

### ISSUE THREAD

**Issue by adalidortiz** [sagiadinos/garlic-player#13]
I'am testing and learning. The Android version support  bigscreen (when multi monitor) parameter with HDMI hub and 2 or more screens like Windows 10?

X96 Android TV Box
Android 5 or 7

Gracias !!!

**Comment by sagiadinos** [comment]
Bigscreen means multi screen which are combined as a large virtual screen. In linux this is called Xinerama and I think Windows names it is the extend mode.

Currently, I have no experiences with multiple screens in Android, but some days ago a customer sends me an interesting Android device with two screens, which can operate separately. I haven't gotten around to looking into it. Do you mean this with HDMI hub?

¡de nada!

**Comment by adalidortiz** [comment]
Thanks for the reply. Yes, with and HDMI hub. I'm testing in Windows 10 with two monitors. My index.smil have two videos loaded locally in c:\garlyc\1.mp4 and 2.mp4 with bigscreen parameters. The videos expand across the monitors very well but now I want to test regions with this sample:
<smil>
  <head>

    <layout>
      <root-layout width="1280" height="720" />
      <region regionName="video" top="0" left="0" width="720" height="480" z-index="1" />
      <region regionName="slideshow" top="0" left="720" width="560" height="480" z-index="1" />
      <region regionName="overlay" top="50" left="50" width="100" height="100" z-index="2" />
    </layout>

  </head>
  <body>

    <par>
      <video src="video1.mp4" region="video" />
      <img src="imagen1.jpg" region="slideshow" />
      <img src="logo.jpg" mediaOpacity="50%" region="overlay" />
    </par>

  </body>
</smil>

Only the videos are displaying. Not the logo or imagen1. Any help?

Saludos desde Tijuana, Mexico.

**Comment by sagiadinos** [comment]
Holà,
Images needs a duration (dur-attribute). You can set a time 
<img src="imagen1.jpg" dur="20s" region="slideshow" />
or
<img src="imagen1.jpg" dur="indefinite" region="slideshow" />

btw.: mediaOpacity is not supported currently, because there are some caveats with videos.
I would suggest to use a png-logo and set the transparency of the image.

**Comment by adalidortiz** [comment]
Woooow !!!
It worked. I'm testing many programs, tricks, etc. to do a low cost digital signage in libraries. Maybe will prepare a talk about it for a regional library association in Baja Mexico. By the way, can you share a tutorial and the smil file used in https://www.youtube.com/watch?v=vWcRfZrVPSA&t=12s 

Thanks.

**Comment by sagiadinos** [comment]
That could be complicated. The SMIL-file came from SmilControl-CMS. The background image is a so-called channel (a commissioned work for a customer). In this case it shows the four nearest German pharmacies. This kind of content creates every day automatically depending on the player location.

The program right bottom is a regular sequential (seq) based playlist. No rocket science. Something like

<seq repeatCount="indefinite">
  <img...
  <video...
  <video..
...
</seq>

You will find a good resource for SMIL here: http://www.a-smil.org

**Comment by adalidortiz** [comment]
Many thanks. With the htm bug resolved I think can do something similar.

Muchas gracias !

**Comment by adalidortiz** [comment]
Done !
http://www.biblioteca.iberotijuana.edu.mx/images/garlic_signage.jpg
Gracias mil.
