### ISSUE TITLE
html or url sintax

### ISSUE THREAD

**Issue by adalidortiz** [sagiadinos/garlic-player#14]
Please, help me, how can load a local html page or external html URL. What is the correct sintax if using regions like the sample in my other post?

<smil>
  <head>

    <layout>
      <root-layout width="1024" height="768" />
      <region regionName="video" top="0" left="0" width="720" height="480"/>
      <region regionName="slideshow" top="481" left="0" width="560" height="400"  />
      <region regionName="overlay" top="50" left="50" width="100" height="110" />
      <region regionName="r" top="481" left="561" width="500" height="300" /> (**HERE**)
    </layout>

  </head>
  <body>

    <par>
      <video src="1.mp4" dur="indefinite" region="video" fit="fill" />
      <img src="lobos.jpg" dur="indefinite"  region="slideshow" fit="fill" />
      <img src="logo.jpg"  dur="indefinite" region="overlay"  />
      <ref src="http://www.biblioteca.iberotijuana.edu.mx/movil/index.html" type="text/html" dur="indefinite" region="r" fit="fill"/> (**HERE**)
	  
	</par>

  </body>
</smil>

**Comment by sagiadinos** [comment]
Your syntax was correct. There was a bug, which should now be fixed in v0.3.0.4151
You can get it from the CI builds in 
https://garlic-player.com/downloads/ci-builds/

**Comment by adalidortiz** [comment]
Will test.

Gracias.
