### ISSUE TITLE
Help / Launch player fullscreen and second screen

### ISSUE THREAD

**Issue by adalidortiz** [sagiadinos/garlic-player#15]
How can I start Garlic-Player in a screen 2 or 3 ?
This is the desktop shortcut. The " -m fullscreen " work fine but if add " -s2 " to launch the player in  screen 2 it has no effect.

Windows 10 64
"C:\Program Files (x86)\garlic-player\start_garlic.bat" -m fullscreen -s 2

Also, Garlic-Player support Atom processor?

Gracias.

**Comment by sagiadinos** [comment]
The -s x parameter seems to be buggy. I will fix it until the weekend.

Garlic-Player supports for Windows only 64Bit. So if Atom is 64 Bit-CPU and operates with a 64Bit Windows the player should work.

**Comment by adalidortiz** [comment]
Many thanks !!!

**Comment by sagiadinos** [comment]
Bug is fixed from v0.3.0.419 and above -s 0 (default) is always the primary screen

**Comment by adalidortiz** [comment]
Gracias !!!

**Comment by adalidortiz** [comment]
Hi, testing Garlic player parameters. -s 0 or 1 or 2 works fine but if combined with another like "-m fullscreen" only works the first:
"C:\Program Files (x86)\garlic-player\start_garlic.bat" -s 1 -m fullscreen
Launch the player in screen 1 as indicated but not fullscreen.

If change order:
"C:\Program Files (x86)\garlic-player\start_garlic.bat" -m fullscreen -s 1
Launch the player in the whole screen but not in the desired screen. The launcher shows in default screen.

**Comment by sagiadinos** [comment]
Fixed as issue #16 in https://github.com/sagiadinos/garlic-player/issues/16
