### ISSUE TITLE
Fullscreen and screen number not work

### ISSUE THREAD

**Issue by adalidortiz** [sagiadinos/garlic-player#16]
Hi, testing Garlic player parameters. -s 0 or 1 or 2 works fine but if combined with another like "-m fullscreen" only works the first:
"C:\Program Files (x86)\garlic-player\start_garlic.bat" -s 1 -m fullscreen
Launch the player in screen 1 as indicated but not fullscreen.

If change order:
"C:\Program Files (x86)\garlic-player\start_garlic.bat" -m fullscreen -s 1
Launch the player in the whole screen but not in the desired monitor. The launcher shows in default screen.

This is the version:
  | garlic-player-win64-v0.3.0.422.exe | 2020-03-02 02:00 | 87M |

**Comment by sagiadinos** [comment]
Fullscreen was not moved first. It should be fixed now.
Wait some minutes until the CI server builds the garlic-player-win64-v0.3.0.423.exe.
But it could be also a problem in the start_garlic.bat

I currently do not have a multi screen windows for testing.
Tell me if it works.

**Comment by adalidortiz** [comment]
Mil Gracias !!!

I will test and give you feedback.

**Comment by adalidortiz** [comment]
It worked as you sugest

**Comment by adalidortiz** [comment]
Thanks !!!
garlic-player -s 1 -m fullscreen

**Comment by sagiadinos** [comment]
you are welcome
