### ISSUE TITLE
Raspberry Pi version planned ?

### ISSUE THREAD

**Issue by adalidortiz** [sagiadinos/garlic-player#17]
I´am very happy with garlic-player. Are you planned a Raspberry Pi version?

Many libraries here in Mexico have no money to buy a digital signage solution and expensive equipment to implement this kind of technology.

Gracias !!

**Comment by sagiadinos** [comment]
Last summer I test RPI4, but it was not stable enough (overheatung) at that time. I also got some tests with RPI 3 and the Zero but it was not satisfying with the video libs I use.

In my opinion there is another caveat! 
So I recommend not to use a Raspberry Pi for Digital Signage at this moment. Especially not with apps like garlic-player which writes permanently and intensive log files for reporting and statistics. Sooner or later this will destroy standard microSD-Cards which are optimized only for reading. 
Some years ago I got some negative experiences with another player and consumer USB-Sticks.
That is beside of the video issues with rpi3 one of the reasons why I did not look after a Raspberry version. 

Look here if you need more detailed information on this topic.
https://smil-control.com/digital-signage-and-raspberry-pi/

My current suggestion is to use a cheap multimedia player based on Android with eMMC-Flash.
Search for at least Android 7.1.1,  2GB RAM and 8GB Flash (16GB and more if you need to play 4K Videos). The prizes should start with about 50 US$. But keep in mind that is cheap hardware without real support and updates.

Do not misunderstand me: The Raspberry Pi 4 in my opinion is a gorgeous machine and I normally prefer Linux over Android. If a future RPI include or supports eMMC-Flash, it would be a perfect match for Digital Signage.

**Comment by adalidortiz** [comment]
Thanks for the explanation. Actually I'm tested garlic-player on an Android TV box and work very well. 

Many thanks !!!
