### ISSUE TITLE
Install error

### ISSUE THREAD

**Issue by adalidortiz** [sagiadinos/garlic-player#19]
Testing the latest CI-Build on Windows 7 and Windows 10 the installer show an error installing the libraries ...vcredist_x64 :

![error](https://user-images.githubusercontent.com/61249268/76887375-6da54f00-683f-11ea-9698-c49f111a1696.jpg)

Gracias.

**Comment by sagiadinos** [comment]
AFAIK. You can ignore the error. This means that Visual Studio Redistributable is already installed on your system.

https://github.com/sagiadinos/garlic-player/issues/10

**Comment by adalidortiz** [comment]
Gracias !!!
