### ISSUE TITLE
Error while loading shared libraries: libicui18n.so.56: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by salarelv** [sagiadinos/garlic-player#21]
**Describe the bug**
Missing library libicui18n under Kubuntu 21.04

**To Reproduce**
Run sh garlic.sh under Kubuntu (probably any Ubuntu).

**Comment by sagiadinos** [comment]
Hello,
Did you compile it via [Tutorial](https://github.com/sagiadinos/garlic-player/wiki/HowTo-Build-with-Debian-10-(Buster)-and-Ubuntu-18.04) or did you use the binaries from [player-website](https://garlic-player.com)?

If you installed the binaries:
They are built on a Debian 10 system.  Debian 10 use libicu63. Ubuntu has libicu67.
Maybe installing via apt would help.

In general, it is recommended to build the Linux version manually.
