### ISSUE TITLE
How are the settings used?

### ISSUE THREAD

**Issue by jf133** [sagiadinos/garlic-player#24]
Hi, I'm playing around with garlic-player.app (on mac). If I delete the .app file and then download a new one it seems to keep track of the settings. Where are the settings stored for garlic-player.app?

**Comment by jf133** [comment]
found two places:
~/Library/Application Support/garlic-player
~/Library/Caches/garlic-player/

Can you elaborate on how/why these are used?

Thank you!
J

**Comment by sagiadinos** [comment]
There is also another dir/file on macOS and Linux
~/.config/SmilControl/garlic-player.ini
This file stores the UUID and some other config temporary parameter like the content-url, the position of the last used smil-file and the task-id needed for update, resets and other maintenance when used with a launcher (currently only android)

~/Library/Application Support/garlic-player
used for the log-files in logs
QtWebengine also stores the web cache there.

~/Library/Caches/garlic-player/
These are the cached files when using garlic-player with a http/https url

I will create a Wiki entry for this directories.

**Comment by sagiadinos** [comment]
Here are the files locations and descriptions for every supported operating system. 

https://github.com/sagiadinos/garlic-player/wiki/Directories-in-Android,-Linux,-macOS,-and-Windows
