### ISSUE TITLE
iCal -> Wallclock repeat implementation

### ISSUE THREAD

**Issue by jf133** [sagiadinos/garlic-player#26]
Hi -- 

I like this project and interested in its extensive use. Curious, is there a way to implement rrule for easy datetime interpretation of repeating of slides, etc? 

Thank you!

JF

**Comment by sagiadinos** [comment]
Hello JF,

I am uncertain if I understood what you mean with "datetime interpretation of repeating".

There is a "begin" and "end" attribute in SMIL. There you can trigger repeats  based on datetime (wallclock).
http://www.a-smil.org/index.php/Wallclock
https://www.w3.org/TR/SMIL3/smil-timing.html#q31

In the garlic-palyer /test/data/smil/ directory you will find some examples like this here:
https://github.com/sagiadinos/garlic-player/blob/master/tests/data/smil/par/5_wallclock.smil

Hope this helps.

**Comment by jf133** [comment]
Hi Niko -- I was essentially asking for a way to convert ical's repeat rule into the wallclock format to understand format for smil. 

for example: DTSTART:20211220T020000Z
RRULE:FREQ=WEEKLY;UNTIL=20220131T120000Z;COUNT=30;INTERVAL=1;WKST=MO would translate smartly into wallclock. Is there such a thing?

**Comment by jf133** [comment]
I'm going to try to use the Wall clock conversion. 

Thank you
JF

**Comment by sagiadinos** [comment]
Oh, I overseen this.

> Is there such a thing that smil can accept?

Yes, As I understand, wallclock and the repeat periods cover this. Periods have the same syntax [as time intervals](https://en.wikipedia.org/wiki/ISO_8601#Time_intervals) of the iso-8601 date.
e.g.
P1Y2M10DT2H30M
