### ISSUE TITLE
mediaAlign not working

### ISSUE THREAD

**Issue by jf133** [sagiadinos/garlic-player#28]
Hi -- just curious if mediaAlign was implemented as its not working for me? Or stated another way, how would I be able to align content according to smil spec here: https://www.w3.org/TR/SMIL2/layout.html#adef-mediaAlign 

Use case: I have an image (or a video) that I want to align to the right middle of the screen. How would I be able to accomplish that?

If it's implemented, would it be possible to provide a working example? 

Thanks so much!
JF

**Comment by sagiadinos** [comment]
Hi jf,
There is a fork from  [Paul Bozan](https://github.com/paulbozans/garlic-launcher) which implements this. But it works currently only for images not for videos. That one reason I have not back ported it until now. The video widget seems not to support this positionings.

greetings
Niko

**Comment by jf133** [comment]
Are you planning to implement either or both? I would need it in case
images are smaller sized.

Also are you able to implement for videos?

JF

**Comment by jf133** [comment]
I don’t see where it’s implemented. Also, can you pull it in?

Thank you!

**Comment by sagiadinos** [comment]
Hi,

It is now correct implemented for QML and widget player. Video aligment seems to be not possible with Qt-Lib.

**Comment by jf133** [comment]
Thank you! Do you know if it was compiled for all binaries?

**Comment by sagiadinos** [comment]
Every commit into GitHub will be built automatically for every supported OS.

You find them on https://garlic-player.com/index.html#downloads under Latest Developer Releases
or with history on https://garlic-player.com/downloads/ci-builds/

I delete the historic dev-builds from time to time.

**Comment by jf133** [comment]
thank you!
