### ISSUE TITLE
How to build garlic-player for Odroid C4?

### ISSUE THREAD

**Issue by bladerunner2020** [sagiadinos/garlic-player#29]
I would like to try garlic-player with Odroid C4 (arm64, ubuntu OS).
Is there any instruction how to build it?

**Comment by sagiadinos** [comment]
In the Wiki is an [HowTo](https://github.com/sagiadinos/garlic-player/wiki/HowTo-Build-with-Debian-10-(Buster)-and-Ubuntu-18.04)

**Comment by bladerunner2020** [comment]
Thanks, I missed this page.
Failed to install libqtav-dev

```bash
root@odroid:~# sudo apt install libqtav-dev
Reading package lists... Done
Building dependency tree
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 libqtav-dev : Depends: libqtav1 (= 1.13.0+ds-1build2) but it is not going to be installed
               Depends: libqtavwidgets1 (= 1.13.0+ds-1build2) but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
```

**Comment by sagiadinos** [comment]
That is an error message about unmet dependencies:
There must be something wrong with the Ubuntu installation/package systeme:

https://packages.ubuntu.com/en/focal/libqtav-dev is in universe

Is "universe" activated in Ubuntu package manager?

Did a sudo apt-get install -f <package-name> helps?

You can also try:
sudo apt-get update
sudo apt-get clean
sudo apt-get autoremove

Here is another tutorial for unmet dependecies in Ubuntu.
https://net2.com/how-to-fix-unmet-dependencies-error-in-ubuntu/
