### ISSUE TITLE
invalid seq begin/end causes player to hang

### ISSUE THREAD

**Issue by jf133** [sagiadinos/garlic-player#31]
Specifying invalid seq tag causes player to hang:

example is using this:

`<seq begin="wallclock(R/2022-03-29T07:00:00/P0H)" end="wallclock(R/2022-03-29T22:00:00/P0H)">`

The expected behavior, I would think, would be to display nothing and continue to poll for smil as usual.
Also something should be logged to event_log.xml saying there's an error loading smil with a meaningful message.

In general, the player should never hang but continue to poll. I can imagine a nighmare scenario if a bug in creating SMIL comes about it could freeze all players.

**Comment by sagiadinos** [comment]
I think the best solution with a P0H is to discard the repeats. In this case, the begin will fire a start on 2022-03-29T07:00:00 and an end trigger on 2022-03-29T22:00:00.

**In general, the player should never hang but continue to poll. I can imagine a nighmare scenario if a bug in creating SMIL comes about it could freeze all players.**

Full Ack! There is a mechanism required that in the case of a non-valid XML and no previous index.smil is in cache an alternative SMIL will be displayed.
That would also cover #22

**Comment by jf133** [comment]
Agreed on both counts

**Comment by sagiadinos** [comment]
Bug is fixed in this commit:

https://github.com/sagiadinos/garlic-player/commit/d386f0b5b6dc5170490b761a5b2d9bb6ca828186

You can download in latest developer release or here: https://garlic-player.com/downloads/ci-builds/
Build 602
