### ISSUE TITLE
refreshing smil after startime does not trigger playback

### ISSUE THREAD

**Issue by jf133** [sagiadinos/garlic-player#32]
Given a seq that looks like this:

`<seq repeatCount="indefinite" begin="wallclock(R/2022-03-29T17:16:00/P1D)" end="wallclock(R/2022-03-29T18:00:00/P1D)">`

if refreshing index.smil after 17:16:00 (but before 18:00:00) it does not start to play/loop (as the trigger time has passed, I guess?)

Expected behavior is that it starts to play/loop right away as it's within the begin to end period.

**Comment by sagiadinos** [comment]
Assuming that the seq is in active/reachable state.
Yes, the correct behavior on a playlist start between 17:16:00 and 18:00:00 should be to enter the seq.

It seems there is a bug. Can you attach me the complete index.smil, please?

**Comment by jf133** [comment]
The example I'm using is below (sensitive info removed). Appreciate your feedback on the construction, as I'm new to SMIL:

`<?xml version="1.0" encoding="UTF-8"?>
<smil>
    <head>
        <meta http-equiv="Refresh" content="30"/>
        <layout>
            <root-layout width="3840" height="2160"/>
            <region xml:id="fullScreen" width="3840px" height="2160px" left="0px" top="0px" z-index="0" mediaAlign="center" backgroundColor="#000000" />
            <transition xml:id="fade" type="fade" subtype="crossfade" dur="5s" />
        </layout>
    </head>
    <body systemComponent="http://www.w3.org/1999/xhtml">
    <par dur="indefinite">
         <seq repeatCount="indefinite" begin="wallclock(R/2022-03-29T17:16:00/P1D)" end="wallclock(R/2022-03-29T18:00:00/P1D)">
<img src="https://xxxxx/file1.jpg" fit="meetBest" fill="transition" region="fullScreen" dur="5s"/> 
<video src="https://xxxxxxx/video1.mp4" fit="fill" fill="transition" region="fullScreen" dur="5s"/> 
<text src="https://xxxxxxx" fit="meetBest" fill="transition"  region="fullScreen" dur="5s"/>
 </seq> 
    </par>
    </body>
</smil>
`

**Comment by jf133** [comment]
Another expected behavior:

Let's say the start time & sequence is like this 
16:00:00 start time
10 min slide 1 (ends at 16:10:00)
20 min slide 2 (ends at 16:30:00)
15 min slide 3 (ends at 16:45:00)
15 min slide 4 (ends at 17:00:00)
17:00:00 end time 

For proper synchronization, if the player were to start at 16:35 it should start playing slide 3 with 5 min already elapsed and if player were to start at 16:47:00 it should start playing slide 4 with two minutes already elapsed.

**Comment by sagiadinos** [comment]
I cannot reproduce it. Your example works on v0.5.0.601 (current dev version).

For the second question, I created a par sequence started 
from 23:30:00 then every minute an image change
When started player at 23:34:20 correct number 5 is shown.

Do you try it with the garlic 0.5.0 stable or the current dev version? There were some fixes in teh meanwhile.

Here is my test smil. The images are from test directory.

You can also try https://saghiadinos.de/garlic-test/issues/32.smil as Content-Url

<?xml version="1.0" encoding="UTF-8"?>
<smil>
	<head>
		<meta http-equiv="Refresh" content="30"/>
		<layout>
			<root-layout width="1920" height="1080"/>
			<region xml:id="fullScreen" width="1920px" height="1080px" left="0px" top="0px" z-index="0" mediaAlign="center" backgroundColor="#ff00ff" />
		</layout>
	</head>
	<body systemComponent="http://www.w3.org/1999/xhtml">
		<par dur="indefinite">
			<img src="../images/0001.jpg" region="fullScreen" begin="wallclock(R/2022-03-29T23:30:00/P1D)" end="wallclock(R/2022-03-29T23:31:00/P1D)" />
			<img src="../images/0002.jpg" region="fullScreen" begin="wallclock(R/2022-03-29T23:31:00/P1D)" end="wallclock(R/2022-03-29T23:32:00/P1D)" />
			<img src="../images/0003.jpg" region="fullScreen" begin="wallclock(R/2022-03-29T23:32:00/P1D)" end="wallclock(R/2022-03-29T23:33:00/P1D)" />
			<img src="../images/0004.jpg" region="fullScreen" begin="wallclock(R/2022-03-29T23:33:00/P1D)" end="wallclock(R/2022-03-29T23:34:00/P1D)" />
			<img src="../images/0005.jpg" region="fullScreen" begin="wallclock(R/2022-03-29T23:34:00/P1D)" end="wallclock(R/2022-03-29T23:35:00/P1D)" />
			<img src="../images/0006.jpg" region="fullScreen" begin="wallclock(R/2022-03-29T23:35:00/P1D)" end="wallclock(R/2022-03-29T23:36:00/P1D)" />
			<img src="../images/0007.jpg" region="fullScreen" begin="wallclock(R/2022-03-29T23:36:00/P1D)" end="wallclock(R/2022-03-29T23:37:00/P1D)" />
			<img src="../images/0008.jpg" region="fullScreen" begin="wallclock(R/2022-03-29T23:37:00/P1D)" end="wallclock(R/2022-03-29T23:38:00/P1D)" />
			<img src="../images/0009.jpg" region="fullScreen" begin="wallclock(R/2022-03-29T23:38:00/P1D)" end="wallclock(R/2022-03-29T23:39:00/P1D)" />
			<img src="../images/0010.jpg" region="fullScreen" begin="wallclock(R/2022-03-29T23:39:00/P1D)" end="wallclock(R/2022-03-29T23:40:00/P1D)" />
		</par>
	</body>
</smil>
