### ISSUE TITLE
Error while building

### ISSUE THREAD

**Issue by brightscripters** [sagiadinos/garlic-player#33]
Attempted to build on Chromebook without success.

Project ERROR: Unknown module(s) in QT: xmlpatterns
make: *** [Makefile:136: sub-garlic-lib-make_first-ordered] Error 3

Could not install
sudo apt install qt5-default
...
E: Package 'qt5-default' has no installation candidate

Installed instead but not sure it is good enough
sudo apt install qtbase5-dev qtchooser qt5-qmake qtbase5-dev-tools

Any idea?

**Comment by sagiadinos** [comment]
I am not familiar with Chrome OS. Thought it was based on Gentoo Linux, so I'm wondering about apt as Gentoo use emerge as package manager.

try 
apt install libqt5xmlpatterns5-dev 

or do an apt search xmlpattern to find out the correct package name

One remark: This will compile only until qt5.15.x as  in >= Qt6 XML patterns functionality is removed.
I am looking to replace QXmlPatterns with another validator until the end of the year.

**Comment by brightscripters** [comment]
The suggested install seemed to help. Now getting a different error.

g++: fatal error: Killed signal terminated program cc1plus
compilation terminated.
make[1]: *** [Makefile:4074: base_manager.o] Error 1
make[1]: *** Waiting for unfinished jobs....
make[1]: Leaving directory '/home/udi/smil/garlic-player/build/garlic-lib'
make: *** [Makefile:136: sub-garlic-lib-make_first-ordered] Error 2

**Comment by sagiadinos** [comment]
sorry that was wrong. issue #31 was fixed.

**Comment by sagiadinos** [comment]
That sounds like a compiler crash.

Some guesses:
Do you have enough space/ram/swap on the machine?
You do not compile as root?

If you are familiar with qtcreator you can also try to compile manually.
The order is:
1. zlib
2. quazip
3. garlic-lib
4. player-widget

**Comment by brightscripters** [comment]
Thanks for that.
That computer could have ran out of memory or something. I'll try on a more capable one.
I'm not familiar with the QT workflow.
For now I'll use the pre built Mac version and take smil-control for a spin.
