### ISSUE TITLE
Mac player not presenting content

### ISSUE THREAD

**Issue by brightscripters** [sagiadinos/garlic-player#34]
**Describe the bug**
Launched player
Control+S
Saw SMIL index url
Pressed Enter
No response

**Desktop (please complete the following information):**
 - OS: MacOS 10.15.7
Player ver: v0.5.0.566

Terminal showing upon exit
Segmentation fault: 11

**Comment by sagiadinos** [comment]
Ups. I have overseen the report.
I use a MacMini with Catalina 10.15.7 as a build server. Just tested with 566. 

Do you use a local SMIL-File? Could you please send me the SMIL?
