### ISSUE TITLE
garlic crashes on keypress when smil hasn't downloaded yet

### ISSUE THREAD

**Issue by jf133** [sagiadinos/garlic-player#35]
**Describe the bug**
When I run freshly compiled master it crashes with Segmentation fault at Enter keypress

**To Reproduce**
Followed instructions on the how to build garlic on wiki. 
Everything compiled. 
I ran the following bash script (without any params), I specified a random URL for testing (see below in config). 
After the white screen came up (which I thought would be black) I pressed any key and get the segmentation fault:

```
xxx@ubuntu:~/.config/SmilControl$ ~/garlic-player/build/bin/garlic.sh
/home/xxx/garlic-player/build/bin/garlic.sh: line 4: 125622 Segmentation fault      (core dumped) /home/xxx/garlic-player/build/bin/garlic-player $1 $2
```

garlic.sh
-------
```
#!/bin/bash

export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/home/xxx/garlic-player/build/lib
/home/xxx/garlic-player/build/bin/garlic-player $1 $2
#comment out for more debug informations
export QT_LOGGING_RULES="*.debug=false"

exit 0; 
```
------

**Expected behavior**
Black screen, no actions

config/log files:

garlic-player.ini:
```
[General]
cleanupInterval=60000
index_uri=http://someone.something.com
last_played_index_path=/home/xxx/.cache/garlic-player/index.smil
maxMultiPartSize=10000000
maxRequestSize=16000
maxThreads=4
minThreads=1
player_name=momma
port=8080
readTimeout=60000
uuid=74319e09-7683-49f2-b389-a2c6c549422f
```

debug.log:
```
2022-06-22 12:54:55,388 informational default (0)"garlic-player: v0.5.0.567"  Operating System: "linux"
2022-06-22 12:54:55,388 informational Screen (0)Monitor:  "" "Virtual-1"  Geometry: QRect(72,27 1728x919)
2022-06-22 12:54:55,388 informational Screen (0) DisplayGeometrie x: 72 y: 27 width: 1728 height: 919
```

event_log.xml:
```
2022-06-22 12:54:55,388 informational default (0)"garlic-player: v0.5.0.567"  Operating System: "linux"
2022-06-22 12:54:55,388 informational Screen (0)Monitor:  "" "Virtual-1"  Geometry: QRect(72,27 1728x919)
2022-06-22 12:54:55,388 informational Screen (0) DisplayGeometrie x: 72 y: 27 width: 1728 height: 919
```

**Comment by sagiadinos** [comment]
garlic.sh is correct.

Unfortunately, I cannot reproduce it, currently.

Commit [8eaaaaf3776a8476fa318eed3994816228555556](https://github.com/sagiadinos/garlic-player/commit/8eaaaaf3776a8476fa318eed3994816228555556) tested

installed Virtual Kubuntu 22.04 compile player and run after key press
Installed Ubuntu 20.04 in Parallels on M1 Mac, compile player and run without issues after key press

sudo apt install libqtav-dev git libqt5xmlpatterns5-dev qtwebengine5-dev g++ make 

Could you please send me the SMIL file you use?

**Comment by jf133** [comment]
I was able to get everything compiled. Thank you. I think I isolated the bug. If you specify a **random URL** for the index (or a smil has not yet downloaded) and press any key when the white screen appears it will crash. It does not crash after it gets a smil.

**Comment by sagiadinos** [comment]
ok. Thank you. I will fix this asap.

**Comment by jf133** [comment]
Can you also make the background black by default during this loading time?

**Comment by jf133** [comment]
Hey Niko -- any word on if this fixable?

**Comment by sagiadinos** [comment]
Hi,
I forgot to set a notification, as there were some fixes in the last week. There was also a crash when the playlist ended while testing, which should be the same bug you described here. You can check out current version.

**Comment by jf133** [comment]
I tried it and it still crashed.

Specify any random URL and hit OK. After white screen comes push any
button.  It still crashes.

Appreciate your attention to this.

JF
