### ISSUE TITLE
Incorrect parsing of content paths

### ISSUE THREAD

**Issue by disansk** [sagiadinos/garlic-player#38]
If I insert a link to the video stream, it is glued to the path along which the smil playlist is located

The playlist is located at the URL:
http://smil.test.local/smil/data/smil/body/simple.smil

The video stream is located at:
rtsp://172.29.30.131:554/

I insert the playback of the stream:
`<video src="rtsp://172.29.30.131:554/" dur="30s" />`

In event_log.xml I see the line:
`<event><eventType>error</eventType><eventTime>2023-03-03T10:15:34+07:00</eventTime><eventSource>ContentManager</eventSource><eventName>FETCH_FAILED</eventName><metadata><meta name="resourceURI" content="http://smil.test.local/smil/data/smil/body/**rtsp://172.29.30.131:554/**"/><meta name="errorMessage" content="Error transferring http://smil.test.local/smil/data/smil/body/rtsp://172.29.30.131:554/ - server replied: Not Found"/><meta name="transferLength" content="0"/></metadata></event>`

**Comment by sagiadinos** [comment]
#37

**Comment by sagiadinos** [comment]
#37
