### ISSUE TITLE
Add screenshots to F-Droid

### ISSUE THREAD

**Issue by Korb** [sagiadinos/garlic-player#39]
https://f-droid.org/packages/com.sagiadinos.garlic.player/

![Screenshot_2023_0410_175236](https://user-images.githubusercontent.com/3509797/230926102-b7e3865c-e1c7-47f7-91ee-82ef3b87ddcc.jpg)

**Comment by sagiadinos** [comment]
hi,
maybe you should suggest the 664. or v0.6.0. This is the current stable.

**Comment by Korb** [comment]
Garlic-player screenshots still not showing up in F-Droid app.
