### ISSUE TITLE
Storage permission issues on Android v11+ . " Creating or writing to a non-default top level directory is not allowed!"

### ISSUE THREAD

**Issue by anoop473** [sagiadinos/garlic-player#41]
**" Creating or writing to a non-default top level directory is not allowed!"**. 
Error when running the application on Android 11+ while creating folder for cache & logs when using "QStandardPaths::GenericDataLocation". When changed to "QStandardPaths::AppLocalDataLocation" it seems to work properly, but then the folder location is not accessible.

The stable apk which we can download, somehow works properly. But when creating a new build using QT 5.15.2 it is not working without the above said change.

**Smartphone (please complete the following information):**
 - Device: [e.g. Samsung A22]
 - OS: [e.g. Android 12]

**Additional context**
The stable apk works properly on versions 9, 10, 11 & 12. App folder is getting created in Android/Data directory.

**Comment by sagiadinos** [comment]
Qt5.15.2 has some issues. 

I updated the build dependencies and there are now based on Qt5.15.11, OpenJDk 11 and newer build/gradle tools.
From https://garlic-player.com/downloads/ci-builds/latest_android_player.apk is multi-Abi. It should work now on 11+ as expected. If not, please notify me.

This is only a step stone for the port to Qt6. Need to replace QXmlPatterns first, as it is removed in Qt6.
