### ISSUE TITLE
APK size / per-ABI builds?

### ISSUE THREAD

**Issue by IzzySoft** [sagiadinos/garlic-player#43]
I've just noticed APK size increased quite a lot, and meanwhile exceeds 80 MB. My repo has a limit of 30 MB per app, so this app no longer fits. Currently, APKs are pulled from https://garlic-player.com/downloads/ci-builds/latest_android_player.apk – which are "fat builds". Are there per-ABI builds available? I've just checked, and removing all native libs except for arm64 would bring the APK size below 30 MB again – which would open the possibility to keep e.g. the arm64 build in my repo.

**Comment by sagiadinos** [comment]
Yes, there will be some per-ABI builds later.

**Comment by IzzySoft** [comment]
Please let me know when they are ready – and where to fetch them from. Does "later" have an ETA? I've set myself a reminder for 2024-04-01 hoping that gives you enough room. Which ABI (armeabi or arm64-v8) I shall then pick I leave to you.

**Comment by sagiadinos** [comment]
There is now an automated process for multi-ABI and per ABI builds.

https://garlic-player.com/garlic-player/downloads/android/

arm64-v8a should work on all modern Androids as 64 Bit Arms exists for 10 years,

If you want to be sure, use armeabi-v7a. Newer CPUs are compatible with this.

**Comment by IzzySoft** [comment]
Thanks a lot – and wow, great, totally back into my repo's per-app size limit :star_struck: I'll use the arm64-v8a then here, as several newer 64bit devices start(ed) dropping 32bit support – and I guess the "target audience" will rather be at 64bit devices anyway. Should complaints come in, we can always switch to armeabi.

Switch will be in effect with the next sync around 7 pm UTC.

That said, last question in this context: are there some graphics (icon, screenshots) I could/should include with the listing? I've searched here on Github as well as on your website, but could not find any. Just found [this SVG](https://github.com/sagiadinos/garlic-player/blob/master/misc/garlic-player.svg) which I now added here as icon, but some screenshots would be nice to have.

**Comment by sagiadinos** [comment]
I am preparing a Google play release after next stable with the multiabi version. Then I will create some pictures. But to be honest: as there is no significant UI I do not know what kind of images would fit. :-D

**Comment by IzzySoft** [comment]
> as there is no significant UI I do not know what kind of images would fit. :-D

Hehe, I already assumed that would be the reason. But Play *requires* at least two screenshots – while my repo says "it would be really nice if you could".

Vague idea: you said something with "optional", so there'd be a settings screen (unless those options are done by editing some config file from outside). And there'd be one screen showing some specific content, as the images on your website have it. Makes two and thus Google happy – and I'll gladly take those two then as well.
