### ISSUE TITLE
Thanks for the editor

### ISSUE THREAD

**Issue by adalidortiz** [sagiadinos/garlic-player#44]
Thanks for the editor

**Comment by sagiadinos** [comment]
Hi,

I do not really understand the "thanks for the editor". Do you mean the garlic-creator?

To your previous question. 
Garlic-player supports sound in videos and audio files like wav and mp3.

**Comment by adalidortiz** [comment]
Sorry about mi mistake, the sound it's ok. Yes, thanks for the editor.
Saludos.
