### ISSUE TITLE
Question on permissions

### ISSUE THREAD

**Issue by IzzySoft** [sagiadinos/garlic-player#45]
My APK scanner got a few additional checks implemented in January, and on today's release of Garlic reported:

```
! repo/com.sagiadinos.garlic.player_687.apk declares sensitive permission(s):
 android.permission.CAMERA android.permission.RECORD_AUDIO android.permission.ACCESS_FINE_LOCATION
 android.permission.READ_EXTERNAL_STORAGE*
```

Could you please clarify what they are needed for? I must admit I still do not fully understand what exactly the app is doing, so that might be the reason I cannot answer this question myself :see_no_evil:

PS: `READ_EXTERNAL_STORAGE*` – here the trailing `*` indicates Android granted it implicitly because `WRITE_EXTERNAL_STORAGE` was granted.

Thanks in advance!

**Comment by IzzySoft** [comment]
Today's APK reports the same. Any word?

**Comment by sagiadinos** [comment]
To understand what a digital signage player does, please read this:
[https://smil-control.com/magazine/what-is-a-digital-signage-player/](https://smil-control.com/magazine/what-is-a-digital-signage-player/)

Write external storage is required for [caching](https://garlic-player.com/garlic-player/docs/essentials/caching/) and [logs](https://garlic-player.com/garlic-player/docs/essentials/logs-reports/) functionality.

All these permissions are set automatically by the Qt lib the software based on.

Camera and location will be used in a future version when implementing the SMIL feature "switch" to deliver different content based on gender recognition and location.

**Comment by IzzySoft** [comment]
> To understand what a digital signage player does, please read this:

Thanks! Now I get it :smile:

Storage: Thanks, added!

> Camera and location will be used in a future version

Ah, so those are not active yet. OK.

> content based on gender recognition and location

Will those affected be aware of that? Coming from the "privacy sector", this sounds a bit intrusive – of course depending on the context – and of course no offense meant; asking to set the proper description:

![image](https://github.com/sagiadinos/garlic-player/assets/6781438/c5a7bac9-6834-4748-9d2a-db6ef4c15db2)

Oh, funny: INTERNET is shown twice. Hm, it's declared twice :man_shrugging:

```
package: name='com.sagiadinos.garlic.player' versionCode='690' versionName='v0.6.0.690' platformBuildVersionName='12' platformBuildVersionCode='31' compileSdkVersion='31' compileSdkVersionCodename='12'
install-location:'auto'
sdkVersion:'25'
targetSdkVersion:'29'
uses-permission: name='android.permission.INTERNET'
uses-permission: name='android.permission.WRITE_EXTERNAL_STORAGE'
uses-permission: name='android.permission.ACCESS_NETWORK_STATE'
uses-permission: name='android.permission.CAMERA'
uses-permission: name='android.permission.RECORD_AUDIO'
uses-permission: name='android.permission.ACCESS_FINE_LOCATION'
uses-permission: name='android.permission.INTERNET'
uses-permission: name='android.permission.WAKE_LOCK'
application-label:'garlic-player'
```

**Comment by sagiadinos** [comment]
Double Internet permission should be removed in current release. 

> Will those affected be aware of that? Coming from the "privacy sector", this sounds a bit intrusive – of course depending on the context – and of course no offense meant; asking to set the proper description:

No problem with the question. And you are right. It is a privacy concern, which has to be adressed in some countries. 
[DooH-Systems](https://smil-control.com/magazine/digital-out-of-home/) use sensors since years. 

The people who use garlic-player, will be definitely aware as it will be notified in the feature list. This feature will be of course configurable and based on OpenCV, which is an offline lib. So no data will to externals services.

**Comment by IzzySoft** [comment]
> Double Internet permission should be removed in current release.

Cool, thanks!

Permissions/DooH: so the following permission description for Garlic Player should fit?

```yaml
android.permission.ACCESS_FINE_LOCATION: used to show location-based content with DooH (configurable)
android.permission.CAMERA: used for interactive content with DooH (configurable)
android.permission.RECORD_AUDIO: used for interactive content with DooH (configurable)
```

Or could/should I replace "configurable" with "optional" even?

PS: Thanks to your explanations I get an ever better understanding what this is about. I initially missed out a lot of that, so thanks again for your patience and help!

**Comment by IzzySoft** [comment]
Thanks! Done then:

![image](https://github.com/sagiadinos/garlic-player/assets/6781438/8e92ea0c-840b-4e06-b0a6-0c339384f3ab)

(screenshot's still from the previous release, hence the double-internet is still there. New index will be compiled in about 2h from now, then it will look correctly). If you want the other gaps filled, just let me know what explanations I shall put.

Thanks again – my questions are all answered, so I close the issue now.
