### ISSUE TITLE
config.xml

### ISSUE THREAD

**Issue by designchris** [sagiadinos/garlic-player#49]
I've tried to find out what can be done using config.xml - unfortunately to no avail.
Am I missing something or is this undocumented so far?
Thank you!

**Comment by sagiadinos** [comment]
Hello Chris,

You can use the config.xml to config Android Players with a USB-Stick and also to config player remote.

Take a look here:
http://garlic-player.lan/garlic-player/docs/essentials/maintenance-tasks/

Especially here:

http://garlic-player.lan/garlic-player/docs/essentials/maintenance-tasks/#config-xml

In the latest dev releases, it is also possible to set a daily reboot time and the standby deep.
This works on currently only on Android with garlic-launcher.
A garlic-demon for Linux-based OS is in development.

Docs will be updated in the coming days.

 Regards.

**Comment by designchris** [comment]
Hello Nikolaos,

thank you, I really appreciate your quick reply!

Regards,
Chris
