### ISSUE TITLE
[Question] Rest api push

### ISSUE THREAD

**Issue by santoshgistto** [sagiadinos/garlic-player#50]
**Question**
To make rest api push to the player is both rest client and player should be in the same network ?

**Comment by sagiadinos** [comment]
Assuming I understand right: The player includes an HTTP-server. They can be in different subnets, but client/server should be reachable to each other via port forwarding or routing.

Example: if the player is behind a NAT router, you need to set a port forwarding.

**Comment by sagiadinos** [comment]
I have no experiences with ngrok. So, I do not know if this will bridge between two different networks. Probably yes.
